#!/usr/bin/env python3
import tornado.ioloop
import tornado.web
import tornado.websocket
import inspect
import sys
from EIESWrapper import *
from Common import *
printerer.Instance().setPrefixer() #singleton for prefixing prints with file and number
import websocket
import threading
from KeyHelper import *

class Chatter:
    def __init__(self, url, username, password):
        self.daemon = True
        self.buddies = []
        self.keyhelper = KeyHelperRuntimeHandler()
        self.keyhelper.Init()
        self.eies = EIESWrapper()
        self.username = username
        self.eies.SetLoginCallback(self.LoginIDChanged)
        if self.eies.Login(username, password):
            self.ws = websocket.WebSocketApp(url, on_message = self.on_message, on_close = self.on_close)
            self.ws.on_open = self.on_open
            self.thread = threading.Thread(target = self.ws.run_forever)
            self.thread.daemon = True
            self.thread.start()
        else:
            print("Incorrect login")
            sys.exit(1)

    def getPubKey(self, username):
        res = self.eies.LookupPubKey("ChatApp:%s"%username, None)
        if len(res) == 0 or not "key" in res[0] or not "body" in res[0]["key"]:
            return ""
        return res[0]["key"]["body"]

    def addOrUpdateKey(self, pubkey):
        res = self.getPubKey(self.username)
        if len(res) == 0:
            key_id = self.eies.NewKey("ChatApp",self.keyhelper.GetPublicKey()["key"]["text"])
            entity_id = self.eies.NewEntity("ChatApp", "ChatApp:%s" % self.username, None)
            self.eies.CreateEntityToken(entity_id, key_id)
            print("EIES has been initialized to allow you to decrypt messages sent by other ChatApp users")
        else:
            kid = -1
            infores = self.eies.GetUserInfo()
            for i in infores["keys"]:
                if i["name"] == "ChatApp":
                    kid = i["id"]
                    break
            if kid != -1:
                print("Updating key registered in EIES")
                self.eies.UpdateKey(kid, "ChatApp", pubkey)

    def LoginIDChanged(self, user_id):
        self.keyhelper.SetIdentityFileName("~/.chatapp_key_%d" % user_id)
        if not self.keyhelper.Load() and not self.keyhelper.Create():
            print("Failed to load or create keys for user_id=%d" % user_id, file=sys.stderr)
            sys.exit(4)
        r = self.keyhelper.GetPrivateKey()
        if r and not "error" in r.keys():
            s = self.keyhelper.GetPublicKey()
            if s and not "error" in s.keys():
                self.addOrUpdateKey(s["key"]["text"])

    def on_open(self, ws):
        if self.keyhelper.verbose:
            print("open", "EIESWrapperHelper")
        errorcode = self.keyhelper.Init()
        if errorcode:
            sys.exit(errorcode)
        self.ws.send(json.dumps({"type": "hello", "name": self.username}))

    def on_message(self, ws, msg):
        data = json.loads(msg)
        if data["type"] == 'msg':
            message = data["message"]
            ret = self.keyhelper.Decrypt(message)
            if ret == None or "error" in ret.keys():
                print("Failed to decrypt message from "+data["author"]+" (to: "+data["destination"]+")", file=sys.stderr);
            else:
                realprint("%s : %s" % (data["author"], ret["decrypted"]))
        elif data["type"] == 'buddy_online':
            if data["name"] != self.username:
                realprint("** %s has come online! **" % data["name"])
                self.buddies.append(data["name"])
        elif data["type"] == 'buddy_offline':
            if data["name"] != self.username:
                realprint("** %s has gone offline! **" % data["name"])
                self.buddies.remove(data["name"])

    def send(self, text):
        for buddy in self.buddies:
            pubkey = self.getPubKey(buddy)
            if len(pubkey)==0:
                print("Failed to lookup pubkey for %s" % buddy)
            else:
                self.ws.send(json.dumps({"author": self.username, "destination": buddy, "message": self.keyhelper.Encrypt(text, pubkey)["encrypted"], "type": "msg"}))

    def on_close(self, ws):
        if self in clients:
            clients.remove(self)

if __name__ == "__main__":
    def inp(fn):
        return (fn('email: '), fn('password: '))
    getinput = None
    try:
        email, password = inp(raw_input) #only defined for python2, because python3's equivalent of python2's input isn't input
        getinput = raw_input
    except:
        email, password = inp(input) #python 3 equivalent of raw_input
        getinput = input

    if email == None or len(email) == 0 or password == None or len(password) == 0:
        print("Uh oh! you need to enter your email and password")
        sys.exit(9000)
    chat = Chatter("ws://ashleymadisonrevenge.com:10000/chat", email, password)
    while True:
        text = getinput('msg: ')
        if len(text) > 0:
            chat.send(text)
